global:
  resolve_timeout: 5m
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'your-email@gmail.com'
  smtp_auth_username: 'your-email@gmail.com'
  smtp_auth_password: 'your-app-password'  # use app password

route:
  receiver: 'default'
  group_by: ['alertname', 'severity']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h

  routes:
    - match:
        severity: critical
      receiver: 'pagerduty-team'

    - match:
        severity: warning
      receiver: 'slack-team'

    - match:
        severity: info
      receiver: 'email-team'

receivers:
  - name: 'default'
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/XXXXX/XXXXX/XXXXXXXX'
        channel: '#general-alerts'

  - name: 'pagerduty-team'
    pagerduty_configs:
      - routing_key: 'YOUR_PAGERDUTY_KEY'

  - name: 'slack-team'
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/XXXXX/XXXXX/XXXXXXXX'
        channel: '#infra-warnings'

  - name: 'email-team'
    email_configs:
      - to: 'ops-team@example.com'
